/**
 * @fileoverview gRPC-Web generated client stub for telemetry
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v3.21.12
// source: telemetry.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');

const proto = {};
proto.telemetry = require('./telemetry_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.telemetry.TelemetryServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.telemetry.TelemetryServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.telemetry.SensorData,
 *   !proto.telemetry.Empty>}
 */
const methodDescriptor_TelemetryService_SendData = new grpc.web.MethodDescriptor(
  '/telemetry.TelemetryService/SendData',
  grpc.web.MethodType.UNARY,
  proto.telemetry.SensorData,
  proto.telemetry.Empty,
  /**
   * @param {!proto.telemetry.SensorData} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.telemetry.Empty.deserializeBinary
);


/**
 * @param {!proto.telemetry.SensorData} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.telemetry.Empty)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.telemetry.Empty>|undefined}
 *     The XHR Node Readable Stream
 */
proto.telemetry.TelemetryServiceClient.prototype.sendData =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/telemetry.TelemetryService/SendData',
      request,
      metadata || {},
      methodDescriptor_TelemetryService_SendData,
      callback);
};


/**
 * @param {!proto.telemetry.SensorData} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.telemetry.Empty>}
 *     Promise that resolves to the response
 */
proto.telemetry.TelemetryServicePromiseClient.prototype.sendData =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/telemetry.TelemetryService/SendData',
      request,
      metadata || {},
      methodDescriptor_TelemetryService_SendData);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.telemetry.Empty,
 *   !proto.telemetry.GrpcStats>}
 */
const methodDescriptor_TelemetryService_GetGrpcStream = new grpc.web.MethodDescriptor(
  '/telemetry.TelemetryService/GetGrpcStream',
  grpc.web.MethodType.SERVER_STREAMING,
  proto.telemetry.Empty,
  proto.telemetry.GrpcStats,
  /**
   * @param {!proto.telemetry.Empty} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.telemetry.GrpcStats.deserializeBinary
);


/**
 * @param {!proto.telemetry.Empty} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.telemetry.GrpcStats>}
 *     The XHR Node Readable Stream
 */
proto.telemetry.TelemetryServiceClient.prototype.getGrpcStream =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/telemetry.TelemetryService/GetGrpcStream',
      request,
      metadata || {},
      methodDescriptor_TelemetryService_GetGrpcStream);
};


/**
 * @param {!proto.telemetry.Empty} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.telemetry.GrpcStats>}
 *     The XHR Node Readable Stream
 */
proto.telemetry.TelemetryServicePromiseClient.prototype.getGrpcStream =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/telemetry.TelemetryService/GetGrpcStream',
      request,
      metadata || {},
      methodDescriptor_TelemetryService_GetGrpcStream);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.telemetry.Empty,
 *   !proto.telemetry.GrpcStats>}
 */
const methodDescriptor_TelemetryService_GetStats = new grpc.web.MethodDescriptor(
  '/telemetry.TelemetryService/GetStats',
  grpc.web.MethodType.UNARY,
  proto.telemetry.Empty,
  proto.telemetry.GrpcStats,
  /**
   * @param {!proto.telemetry.Empty} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.telemetry.GrpcStats.deserializeBinary
);


/**
 * @param {!proto.telemetry.Empty} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.telemetry.GrpcStats)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.telemetry.GrpcStats>|undefined}
 *     The XHR Node Readable Stream
 */
proto.telemetry.TelemetryServiceClient.prototype.getStats =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/telemetry.TelemetryService/GetStats',
      request,
      metadata || {},
      methodDescriptor_TelemetryService_GetStats,
      callback);
};


/**
 * @param {!proto.telemetry.Empty} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.telemetry.GrpcStats>}
 *     Promise that resolves to the response
 */
proto.telemetry.TelemetryServicePromiseClient.prototype.getStats =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/telemetry.TelemetryService/GetStats',
      request,
      metadata || {},
      methodDescriptor_TelemetryService_GetStats);
};


module.exports = proto.telemetry;

