version: '3.8'

services:
  gateway:
    build:
      context: .
      target: gateway
    ports:
      - "50051:50051"
      - "8080:8080"
    volumes:
      - ./results:/root/results
    environment:
      - BENCH_MODE=true
    networks:
      - telemetry-net

  benchmark:
    build:
      context: .
      target: sensor
    depends_on:
      - gateway
    environment:
      - APP_MODE=benchmark
    restart: "no"
    networks:
      - telemetry-net


networks:
  telemetry-net:
    driver: bridge