// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/telemetry.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NestedDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,3,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NestedDetail) Reset() {
	*x = NestedDetail{}
	mi := &file_proto_telemetry_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NestedDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NestedDetail) ProtoMessage() {}

func (x *NestedDetail) ProtoReflect() protoreflect.Message {
	mi := &file_proto_telemetry_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NestedDetail.ProtoReflect.Descriptor instead.
func (*NestedDetail) Descriptor() ([]byte, []int) {
	return file_proto_telemetry_proto_rawDescGZIP(), []int{0}
}

func (x *NestedDetail) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *NestedDetail) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *NestedDetail) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type SensorData struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	SensorId        string                 `protobuf:"bytes,1,opt,name=sensor_id,json=sensorId,proto3" json:"sensor_id,omitempty"`
	Temperature     float32                `protobuf:"fixed32,2,opt,name=temperature,proto3" json:"temperature,omitempty"`
	Humidity        float32                `protobuf:"fixed32,3,opt,name=humidity,proto3" json:"humidity,omitempty"`
	Timestamp       int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Tags            []string               `protobuf:"bytes,5,rep,name=tags,proto3" json:"tags,omitempty"`
	Details         []*NestedDetail        `protobuf:"bytes,6,rep,name=details,proto3" json:"details,omitempty"`
	ReadingsHistory map[string]float32     `protobuf:"bytes,7,rep,name=readings_history,json=readingsHistory,proto3" json:"readings_history,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed32,2,opt,name=value"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SensorData) Reset() {
	*x = SensorData{}
	mi := &file_proto_telemetry_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SensorData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SensorData) ProtoMessage() {}

func (x *SensorData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_telemetry_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SensorData.ProtoReflect.Descriptor instead.
func (*SensorData) Descriptor() ([]byte, []int) {
	return file_proto_telemetry_proto_rawDescGZIP(), []int{1}
}

func (x *SensorData) GetSensorId() string {
	if x != nil {
		return x.SensorId
	}
	return ""
}

func (x *SensorData) GetTemperature() float32 {
	if x != nil {
		return x.Temperature
	}
	return 0
}

func (x *SensorData) GetHumidity() float32 {
	if x != nil {
		return x.Humidity
	}
	return 0
}

func (x *SensorData) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *SensorData) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *SensorData) GetDetails() []*NestedDetail {
	if x != nil {
		return x.Details
	}
	return nil
}

func (x *SensorData) GetReadingsHistory() map[string]float32 {
	if x != nil {
		return x.ReadingsHistory
	}
	return nil
}

type GrpcStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AvgLatency    float64                `protobuf:"fixed64,1,opt,name=avg_latency,json=avgLatency,proto3" json:"avg_latency,omitempty"`
	P99Latency    float64                `protobuf:"fixed64,2,opt,name=p99_latency,json=p99Latency,proto3" json:"p99_latency,omitempty"`
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	PayloadSize   int64                  `protobuf:"varint,4,opt,name=payload_size,json=payloadSize,proto3" json:"payload_size,omitempty"`
	Overhead      int64                  `protobuf:"varint,5,opt,name=overhead,proto3" json:"overhead,omitempty"`
	Throughput    float64                `protobuf:"fixed64,6,opt,name=throughput,proto3" json:"throughput,omitempty"`
	MarshalTime   float64                `protobuf:"fixed64,7,opt,name=marshalTime,proto3" json:"marshalTime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GrpcStats) Reset() {
	*x = GrpcStats{}
	mi := &file_proto_telemetry_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrpcStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrpcStats) ProtoMessage() {}

func (x *GrpcStats) ProtoReflect() protoreflect.Message {
	mi := &file_proto_telemetry_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrpcStats.ProtoReflect.Descriptor instead.
func (*GrpcStats) Descriptor() ([]byte, []int) {
	return file_proto_telemetry_proto_rawDescGZIP(), []int{2}
}

func (x *GrpcStats) GetAvgLatency() float64 {
	if x != nil {
		return x.AvgLatency
	}
	return 0
}

func (x *GrpcStats) GetP99Latency() float64 {
	if x != nil {
		return x.P99Latency
	}
	return 0
}

func (x *GrpcStats) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *GrpcStats) GetPayloadSize() int64 {
	if x != nil {
		return x.PayloadSize
	}
	return 0
}

func (x *GrpcStats) GetOverhead() int64 {
	if x != nil {
		return x.Overhead
	}
	return 0
}

func (x *GrpcStats) GetThroughput() float64 {
	if x != nil {
		return x.Throughput
	}
	return 0
}

func (x *GrpcStats) GetMarshalTime() float64 {
	if x != nil {
		return x.MarshalTime
	}
	return 0
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_proto_telemetry_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_telemetry_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_telemetry_proto_rawDescGZIP(), []int{3}
}

var File_proto_telemetry_proto protoreflect.FileDescriptor

const file_proto_telemetry_proto_rawDesc = "" +
	"\n" +
	"\x15proto/telemetry.proto\x12\ttelemetry\"\xb6\x01\n" +
	"\fNestedDetail\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\x12A\n" +
	"\bmetadata\x18\x03 \x03(\v2%.telemetry.NestedDetail.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xe7\x02\n" +
	"\n" +
	"SensorData\x12\x1b\n" +
	"\tsensor_id\x18\x01 \x01(\tR\bsensorId\x12 \n" +
	"\vtemperature\x18\x02 \x01(\x02R\vtemperature\x12\x1a\n" +
	"\bhumidity\x18\x03 \x01(\x02R\bhumidity\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\x12\x12\n" +
	"\x04tags\x18\x05 \x03(\tR\x04tags\x121\n" +
	"\adetails\x18\x06 \x03(\v2\x17.telemetry.NestedDetailR\adetails\x12U\n" +
	"\x10readings_history\x18\a \x03(\v2*.telemetry.SensorData.ReadingsHistoryEntryR\x0freadingsHistory\x1aB\n" +
	"\x14ReadingsHistoryEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x02R\x05value:\x028\x01\"\xec\x01\n" +
	"\tGrpcStats\x12\x1f\n" +
	"\vavg_latency\x18\x01 \x01(\x01R\n" +
	"avgLatency\x12\x1f\n" +
	"\vp99_latency\x18\x02 \x01(\x01R\n" +
	"p99Latency\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\x12!\n" +
	"\fpayload_size\x18\x04 \x01(\x03R\vpayloadSize\x12\x1a\n" +
	"\boverhead\x18\x05 \x01(\x03R\boverhead\x12\x1e\n" +
	"\n" +
	"throughput\x18\x06 \x01(\x01R\n" +
	"throughput\x12 \n" +
	"\vmarshalTime\x18\a \x01(\x01R\vmarshalTime\"\a\n" +
	"\x05Empty2\xf3\x01\n" +
	"\x10TelemetryService\x125\n" +
	"\bSendData\x12\x15.telemetry.SensorData\x1a\x10.telemetry.Empty\"\x00\x129\n" +
	"\n" +
	"StreamData\x12\x15.telemetry.SensorData\x1a\x10.telemetry.Empty\"\x00(\x01\x129\n" +
	"\rGetGrpcStream\x12\x10.telemetry.Empty\x1a\x14.telemetry.GrpcStats0\x01\x122\n" +
	"\bGetStats\x12\x10.telemetry.Empty\x1a\x14.telemetry.GrpcStatsB\tZ\a./protob\x06proto3"

var (
	file_proto_telemetry_proto_rawDescOnce sync.Once
	file_proto_telemetry_proto_rawDescData []byte
)

func file_proto_telemetry_proto_rawDescGZIP() []byte {
	file_proto_telemetry_proto_rawDescOnce.Do(func() {
		file_proto_telemetry_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_telemetry_proto_rawDesc), len(file_proto_telemetry_proto_rawDesc)))
	})
	return file_proto_telemetry_proto_rawDescData
}

var file_proto_telemetry_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_telemetry_proto_goTypes = []any{
	(*NestedDetail)(nil), // 0: telemetry.NestedDetail
	(*SensorData)(nil),   // 1: telemetry.SensorData
	(*GrpcStats)(nil),    // 2: telemetry.GrpcStats
	(*Empty)(nil),        // 3: telemetry.Empty
	nil,                  // 4: telemetry.NestedDetail.MetadataEntry
	nil,                  // 5: telemetry.SensorData.ReadingsHistoryEntry
}
var file_proto_telemetry_proto_depIdxs = []int32{
	4, // 0: telemetry.NestedDetail.metadata:type_name -> telemetry.NestedDetail.MetadataEntry
	0, // 1: telemetry.SensorData.details:type_name -> telemetry.NestedDetail
	5, // 2: telemetry.SensorData.readings_history:type_name -> telemetry.SensorData.ReadingsHistoryEntry
	1, // 3: telemetry.TelemetryService.SendData:input_type -> telemetry.SensorData
	1, // 4: telemetry.TelemetryService.StreamData:input_type -> telemetry.SensorData
	3, // 5: telemetry.TelemetryService.GetGrpcStream:input_type -> telemetry.Empty
	3, // 6: telemetry.TelemetryService.GetStats:input_type -> telemetry.Empty
	3, // 7: telemetry.TelemetryService.SendData:output_type -> telemetry.Empty
	3, // 8: telemetry.TelemetryService.StreamData:output_type -> telemetry.Empty
	2, // 9: telemetry.TelemetryService.GetGrpcStream:output_type -> telemetry.GrpcStats
	2, // 10: telemetry.TelemetryService.GetStats:output_type -> telemetry.GrpcStats
	7, // [7:11] is the sub-list for method output_type
	3, // [3:7] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_telemetry_proto_init() }
func file_proto_telemetry_proto_init() {
	if File_proto_telemetry_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_telemetry_proto_rawDesc), len(file_proto_telemetry_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_telemetry_proto_goTypes,
		DependencyIndexes: file_proto_telemetry_proto_depIdxs,
		MessageInfos:      file_proto_telemetry_proto_msgTypes,
	}.Build()
	File_proto_telemetry_proto = out.File
	file_proto_telemetry_proto_goTypes = nil
	file_proto_telemetry_proto_depIdxs = nil
}
